= Summary
:source-highlighter: coderay

== _Chapter 06_

The core idea in object-oriented programming is to divide programs into smaller pieces, and make each piece responsible for managing its own state.

This way, some knowledge about the way a piece of the program works is kept local to that piece. This way, someone working on the rest of the program does not have to remember or even be aware of that knowledge. And if these details change, only the code directly around it needs to change.

Different pieces of such a program interact with each other through interfaces, which are limited sets of functions or bindings that provide useful functionality at a more abstract level, hiding its precise implementation.

=== The Iterator Interface

The object given to a ``for/of loop`` is expected to be iterable. This means that it has a method named with the ``Symbol.iterator`` symbol (a symbol value defined by the language, stored as a property of the ``Symbol`` function).

When called, that method should return an object that provides a second interface, iterator. 
This is the *actual thing* that iterates. 

It has a next method that returns the ``next result``. 
That result should be an object with a ``value`` property, providing the next value, and a ``done`` property, which should be ``true`` when there are no more results and ``false`` otherwise.

Note that the ``next``, ``value``, and ``done`` property names are plain strings, not symbols. 
Only ``Symbol.iterator``, which is likely to be added to a lot of different objects, is an actual symbol.  

[source, js]
.link:./src/the-iterator-interface/matrix.js[Click]
----
include::./src/the-iterator-interface/es6/matrix.mjs[tag=code]
----

.link:./src/the-iterator-interface/index.html[Click]
[source, html]
include::./src/the-iterator-interface/index.html
